const mongoose = require('mongoose');

const portfolioSchema = new mongoose.Schema({
  technicianId: { type: String, ref: 'User', required: true },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  imageUrl: { type: String, required: true },
  category: { type: String, required: true },
  // Set when the item was generated automatically from a completed service request.
  requestId: { type: String, ref: 'ServiceRequest', default: null },
  autoGenerated: { type: Boolean, default: false },
}, {
  timestamps: true,
});

portfolioSchema.index({ technicianId: 1 });
portfolioSchema.index({ requestId: 1 });

module.exports = mongoose.model('Portfolio', portfolioSchema);
