const Portfolio = require('../entities/Portfolio');
const ServiceRequest = require('../entities/ServiceRequest');

// Picks the best available image to represent a completed job.
function pickImage(request) {
  return (
    request.completionPhotoUrl ||
    (Array.isArray(request.imageUrls) && request.imageUrls[0]) ||
    (Array.isArray(request.thumbnailUrls) && request.thumbnailUrls[0]) ||
    null
  );
}

// Creates a portfolio entry from a completed service request (idempotent per request).
// Skips silently when the request has no technician or no usable image.
async function addCompletedRequestToPortfolio(request) {
  try {
    if (!request || !request.technicianId) return null;

    const requestId = request._id ? request._id.toString() : (request.id || null);
    if (!requestId) return null;

    // Avoid duplicates: one auto entry per request.
    const existing = await Portfolio.findOne({ requestId });
    if (existing) return existing;

    const imageUrl = pickImage(request);
    if (!imageUrl) return null; // Portfolio requires an image.

    return await Portfolio.create({
      technicianId: request.technicianId,
      title: request.title,
      description: request.description || '',
      imageUrl,
      category: request.category,
      requestId,
      autoGenerated: true,
    });
  } catch (err) {
    console.error('[portfolio] auto-add failed:', err.message);
    return null;
  }
}

// Ensures every completed job of a technician has an auto portfolio entry.
// Used to retro-fit jobs finished before auto-generation existed.
async function backfillTechnicianPortfolio(technicianId) {
  try {
    if (!technicianId) return;

    const completed = await ServiceRequest.find({
      technicianId,
      status: 'completed',
    }).lean();
    if (!completed.length) return;

    const existing = await Portfolio.find({
      technicianId,
      requestId: { $ne: null },
    }).select('requestId').lean();
    const existingIds = new Set(existing.map((p) => p.requestId));

    const docs = [];
    for (const r of completed) {
      const rid = r._id.toString();
      if (existingIds.has(rid)) continue;
      const imageUrl = pickImage(r);
      if (!imageUrl) continue;
      docs.push({
        technicianId,
        title: r.title,
        description: r.description || '',
        imageUrl,
        category: r.category,
        requestId: rid,
        autoGenerated: true,
      });
    }

    if (docs.length) await Portfolio.insertMany(docs);
  } catch (err) {
    console.error('[portfolio] backfill failed:', err.message);
  }
}

module.exports = { addCompletedRequestToPortfolio, backfillTechnicianPortfolio };
